{
 "title": "tupoproxy MtProto proxy",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "user",
    "query": {
     "query": "label_values(tupoproxy_user_connections_total,user)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Total", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "UP",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "tupoproxy_uptime_seconds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total connections",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "increase(tupoproxy_connections_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total connections - failed",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "increase(tupoproxy_connections_bad_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "From clients(bytes)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "increase(sum(tupoproxy_user_octets_from_client))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "From/To clients(bytes)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "increase(sum(tupoproxy_user_octets_from_client))",
     "legendFormat": "from"
    },
    {
     "expr": "increase(sum(tupoproxy_user_octets_to_client))",
     "legendFormat": "to"
    }
   ]
  },
  {
   "title": "To clients(bytes)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "-increase(sum(tupoproxy_user_octets_to_client))",
     "legendFormat": "to"
    }
   ]
  },
  { "title": "By user", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Connections",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "tupoproxy_user_connections_current{user=~\"$user\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 4, "y": 8 },
   "targets": [
    {
     "expr": "tupoproxy_user_connections_current{user=~\"$user\"}",
     "legendFormat": "{{user}}"
    }
   ]
  },
  {
   "title": "More then one IP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "tupoproxy_user_unique_ips_current{user=~\"$user\"} > 1",
     "legendFormat": "{{user}}"
    },
    {
     "expr": "tupoproxy_user_unique_ips_recent_window{user=~\"$user\"} > 1",
     "legendFormat": "{{user}} -w"
    }
   ]
  },
  {
   "title": "To",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "increase(tupoproxy_user_octets_to_client{user=~\"$user\"})",
     "legendFormat": "to {{user}}"
    }
   ]
  },
  {
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "increase(tupoproxy_user_octets_to_client{user=~\"$user\"})",
     "legendFormat": "{{user}}"
    }
   ]
  },
  {
   "title": "From",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "increase(tupoproxy_user_octets_from_client{user=~\"$user\"})",
     "legendFormat": "from {{user}}"
    }
   ]
  },
  {
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "increase(tupoproxy_user_octets_from_client{user=~\"$user\"})",
     "legendFormat": "{{user}}"
    }
   ]
  }
 ]
}